mdx-js/eslint-mdx

- README.md
- package.json
- packages/eslint-mdx/README.md
- packages/eslint-mdx/package.json
- packages/eslint-plugin-mdx/README.md
- packages/eslint-plugin-mdx/package.json
- yarn.lock
> fix: change organization of project repository to mdx-js :tada:

- package.json
- packages/eslint-mdx/package.json
- packages/eslint-plugin-mdx/package.json
- yarn.lock
> fix: add `prepublishOnly` lifecycle script, close #116

- packages/eslint-mdx/src/traverse.ts
- test/no-unescaped-entities.test.ts
Adjacent self-closing tags should be parsed separately instead of combined into a single jsx node.
> fix: self closing tag should not be combined - close #158

- .eslintrc.js
- package.json
- packages/eslint-mdx/package.json
- packages/eslint-mdx/src/helper.ts
- packages/eslint-mdx/src/parser.ts
- packages/eslint-plugin-mdx/package.json
- packages/eslint-plugin-mdx/src/configs/recommended.ts
- packages/eslint-plugin-mdx/src/index.ts
- packages/eslint-plugin-mdx/src/rules/helper.ts
- packages/eslint-plugin-mdx/src/rules/no-jsx-html-comments.ts
- packages/eslint-plugin-mdx/src/rules/no-unescaped-entities.ts
- packages/eslint-plugin-mdx/src/rules/remark.ts
- test/fixtures.test.ts
- test/helper.ts
- tslint.json
- yarn.lock
> fix: compatibility with typescript-eslint

- packages/eslint-mdx/src/parser.ts
- packages/eslint-plugin-mdx/src/rules/helper.ts
- packages/eslint-plugin-mdx/src/rules/remark.ts
- test/__snapshots__/fixtures.test.ts.snap
- test/fixtures/remark.md
- yarn.lock
As `remark-mdx@v2` is [not compatible](https://github.com/mdx-js/mdx/issues/1042) with normal markdown comment syntaxes anymore, so markdown and mdx files should be processed specifically.
@johno @wooorm
> feat: remark-mdx is not compatible with normal markdown syntaxes

- README.md
- packages/eslint-mdx/README.md
- packages/eslint-plugin-mdx/README.md
- packages/eslint-plugin-mdx/src/processors/helpers.ts
- packages/eslint-plugin-mdx/src/processors/index.ts
- packages/eslint-plugin-mdx/src/processors/markdown.ts
- packages/eslint-plugin-mdx/src/processors/options.ts
- packages/eslint-plugin-mdx/src/processors/remark.ts
- packages/eslint-plugin-mdx/src/processors/types.ts
- packages/eslint-plugin-mdx/src/rules/helpers.ts
- test/helpers.test.ts
1. `{index}_` prefix is hard coded at https://github.com/eslint/eslint/blob/master/lib/linter/linter.js#L1303
2. provide ability to disable or custom language mapper, see also https://github.com/eslint/eslint-plugin-markdown/pull/178#issuecomment-801821377
> refactor: move getShortLang outside markdown processor

- .eslintrc.js
- package.json
- packages/eslint-mdx/src/helpers.ts
- packages/eslint-mdx/src/parser.ts
- packages/eslint-mdx/src/types.ts
- packages/eslint-plugin-mdx/src/processors/markdown.ts
- packages/eslint-plugin-mdx/src/processors/types.ts
- test/__snapshots__/fixtures.test.ts.snap
- test/__snapshots__/helpers.test.ts.snap
- test/fixtures.test.ts
- test/fixtures/292.mdx
- test/helpers.test.ts
close #292
The following has been resolved!
<del>
I don't know if there is a better and cleaner way without source `code` or `lines`.
---
OK, I found maybe we have to use this approach because the loc column of start node could be incorrect as described at https://github.com/mdx-js/eslint-mdx/issues/279#issuecomment-791531564, while the start offset is always correct.
</del>
> fix: add helper getPositionAt to fix incorrect loc

- packages/eslint-plugin-mdx/src/rules/helpers.ts
related to disable `remark-lint-file-extension` automatically
> fix: result could be null in `plugins.reduce`

- packages/eslint-plugin-mdx/src/rules/helpers.ts
- packages/eslint-plugin-mdx/src/rules/remark.ts
- test/remark.test.ts
> feat: performance improvement via cache

- package.json
- packages/eslint-plugin-mdx/package.json
- yarn.lock
We are still targeting Node 10 in v1. `synckit` will just use `child_process` as fallback when `worker_threads` is unavailable.
> fix: upgrade synckit v0.3.3 for node compatibility

- package.json
- packages/eslint-mdx/package.json
- packages/eslint-mdx/src/index.ts
- packages/eslint-mdx/src/parser.ts
- packages/eslint-mdx/src/processor.ts
- packages/eslint-mdx/src/types.ts
- packages/eslint-plugin-mdx/package.json
- packages/eslint-plugin-mdx/src/rules/index.ts
- packages/eslint-plugin-mdx/src/rules/remark.ts
- packages/eslint-plugin-mdx/src/rules/types.ts
- packages/eslint-plugin-mdx/src/worker.ts
- test/__snapshots__/fixtures.test.ts.snap
- test/fixtures/336.mdx
- test/helpers.test.ts
- test/parser.test.ts
- test/remark.test.ts
- yarn.lock
> feat: resolve custom remark config on parsing

- packages/eslint-mdx/src/regexp.ts
- test/__snapshots__/fixtures.test.ts.snap
- test/fixtures.test.ts
- test/fixtures/comments.mdx
This change allows comments to contain `--`, which currently they can't, e.g.
```markdown
```
```
1:1  error  Block is redundant  no-lone-blocks
```
I suspect this is already fixed in #284, by upgrading to [micromark](https://github.com/micromark/micromark). This PR adds a test and patches the comment regexp in the meantime.
remark-parse (where this regexp originally came from) [went directly](https://github.com/remarkjs/remark/commit/6b42465526bb15f70d98a0ea0daccea01ffb8004#diff-e74cdd04b8d016ea6e1f4e37bf73e8864f36de36a1409cf43a68dfaf70dfe0ffL13) from our current regexp to micromark, which [doesn't use](https://github.com/micromark/micromark/blob/main/packages/micromark-core-commonmark/dev/lib/html-flow.js) an equivalent.
I used the following to automatically construct this corrected, …
> fix: allow comments to contain `--`

- README.md
- packages/eslint-mdx/README.md
- packages/eslint-mdx/src/parser.ts
- packages/eslint-mdx/src/processor.ts
- packages/eslint-mdx/src/types.ts
- packages/eslint-plugin-mdx/src/rules/remark.ts
- packages/eslint-plugin-mdx/src/worker.ts
- test/parser.test.ts
- test/remark.test.ts
This is just a proposal, and any kind of feedback is welcome.
I add a new `parserOption` named `ignoreRemarkConfig`. It can take two values: `true` or `false`. If it isn't defined, the value is treated as `false`.
What this does? It allow to ignore the remark config that is auto loaded.
Why this can be useful? I just try to improve the workaround commented in the following issue: https://github.com/mdx-js/eslint-mdx/issues/338#issuecomment-1059858710
If I have a remark config in my `package.json` that uses ESM plugins, I can't execute eslint because it throws an error. So, an alternative is to set the remark config in another place where it can't be autoloaded, then run remark, and, afterall, run eslint.
This is what I typically do:
```sh
yarn run remark **/*.mdx --no-stdout -r …
```
> feat: allow to ignore remark config

- .github/workflows/ci.yml
- CONTRIBUTING.md
- package.json
- packages/eslint-mdx/package.json
- packages/eslint-mdx/src/parser.ts
- packages/eslint-mdx/src/worker.ts
- test/__snapshots__/fixtures.test.ts.snap
- test/fixtures/acorn.mdx
- test/fixtures/remark.mdx
- yarn.lock
> fix: throw error with correct loc

- packages/eslint-mdx/src/worker.ts
> fix: same markdown processor cached for .md and .mdx

- packages/eslint-mdx/src/parser.ts
- yarn.lock
> fix: incorrect default ecmaVersion (2022 is unavailable yet)

- .changeset/ninety-bugs-dance.md
- .eslintrc.js
- packages/eslint-mdx/src/worker.ts
- test/__snapshots__/fixtures.test.ts.snap
- test/__snapshots__/parser.test.ts.snap
- test/fixtures.test.ts
- test/fixtures/488.mdx
> fix: incompatible with `react/jsx-sort-props` rule

- .changeset/fifty-windows-sin.md
- .github/workflows/ci.yml
- packages/eslint-plugin-mdx/src/configs/recommended.ts
https://github.com/prettier/eslint-plugin-prettier/releases/tag/v5.1.2
> feat: only enable `prettier/prettier` rule for `eslint-plugin-prettier` `<5.1.2`

- .changeset/strange-balloons-turn.md
- README.md
- packages/eslint-mdx/README.md
- packages/eslint-plugin-mdx/README.md
> fix: incorrect docs due to prettier + mdx v2+ incompatible

- .changeset/new-brooms-visit.md
- packages/eslint-plugin-mdx/src/rules/remark.ts
> fix: undefined place in vFile message causes TypeError

- .changeset/two-eagles-flash.md
- packages/eslint-plugin-mdx/src/rules/remark.ts
> fix: `position` could be `null` actually

- .changeset/eleven-cobras-care.md
- README.md
- packages/eslint-mdx/README.md
- packages/eslint-mdx/src/helpers.ts
- packages/eslint-mdx/src/parser.ts
- packages/eslint-mdx/src/types.ts
- packages/eslint-mdx/src/worker.ts
- packages/eslint-plugin-mdx/README.md
- packages/eslint-plugin-mdx/src/processors/helpers.ts
- packages/eslint-plugin-mdx/src/rules/remark.ts
use native `import()` instead.
> refactor: remove unnecessary `loadEsmModule` helper

- .changeset/smart-pillows-hang.md
- packages/eslint-plugin-mdx/src/processors/helpers.ts
- packages/eslint-plugin-mdx/src/processors/markdown.ts
- packages/eslint-plugin-mdx/src/processors/types.ts
- test/__snapshots__/fixtures.test.ts.snap
- test/fixtures/code-blocks/455.mdx
Introduced by #550, it should be related to auto fixing
> fix: code block filename regexp group names missed

- README.md
- packages/eslint-mdx/README.md
- packages/eslint-plugin-mdx/README.md
Documentation:
- Condense sponsor link markup in [README.md](https://github.com/react-hook-form/react-hook-form/blob/master/README.md) by collapsing `<a>` and `<img>` tags onto single lines to remove blue underlines from sponsor logos.
| Before | After |
|--------|--------|
| ![before](https://github.com/user-attachments/assets/97992f40-be65-4e99-85cd-f492f0139616) | ![after](https://github.com/user-attachments/assets/3b24a235-b807-474f-b33d-3e7c21e6536f) |
> docs: remove blue underline from README.md

- .changeset/wise-spiders-suffer.md
- packages/eslint-mdx/src/types.ts
- packages/eslint-plugin-mdx/src/rules/remark.ts
> fix: pass through `remarkConfigPath` of `parserOptions`
