.eslintrc.js, .travis.yml, README.md, codechecks.yml, package.json, packages/eslint-mdx/README.md, packages/eslint-mdx/src/parser.ts, packages/eslint-plugin-mdx/README.md, packages/eslint-plugin-mdx/package.json, packages/eslint-plugin-mdx/src/configs/base.ts, packages/eslint-plugin-mdx/src/configs/recommended.ts, test/no-unescaped-entities.test.ts, test/no-unused-expressions.test.ts, yarn.lock
BREAKING CHANGE: plugin package renamed
=> feat: rename plugin to `eslint-plugin-mdx`, thanks to @azz

packages/eslint-mdx/src/parser.ts, packages/eslint-mdx/src/types.ts, test/parser.test.ts
=> chore: fix test cases

.gitignore, package.json, packages/eslint-mdx/src/parser.ts, packages/eslint-mdx/src/traverse.ts, packages/eslint-mdx/src/types.ts, test/no-unescaped-entities.test.ts, tsconfig.base.json, yarn.lock
=> fix: use source code to get combined jsx value

packages/eslint-plugin-mdx/package.json
=> chore(engines): update to node version requirement to 10 #248

packages/eslint-mdx/src/helper.ts
improve readability and performance, thanks to @Lucifier129
=> refactor: simplify restoreNodeLocation helper

package.json, packages/eslint-plugin-mdx/src/rules/helpers.ts, yarn.lock
=> fix: cosmiconfig returns null if no config found

packages/eslint-mdx/src/helpers.ts
fix build error
see https://github.com/mdx-js/eslint-mdx/pull/293#issuecomment-803541932
cc @wooorm
=> chore: do not use Array#entries for now

packages/eslint-plugin-mdx/src/processors/markdown.ts, packages/eslint-plugin-mdx/src/processors/remark.ts, test/__snapshots__/fixtures.test.ts.snap
https://github.com/eslint/eslint-plugin-markdown/pull/183#discussion_r606859003
=> feat: split markdown messages in postprocess

package.json, packages/eslint-mdx/package.json, packages/eslint-plugin-mdx/package.json, packages/eslint-plugin-mdx/typings.d.ts, yarn.lock
=> chore: use @types/eslint-plugin-markdown

.github/workflows/ci.yml, package.json, packages/eslint-mdx/package.json, packages/eslint-mdx/src/helpers.ts, packages/eslint-mdx/src/parser.ts, packages/eslint-plugin-mdx/package.json, yarn.lock
=> chore: bump deps, cleanup codes

package.json, test/__snapshots__/fixtures.test.ts.snap, test/fixtures.test.ts, test/fixtures/391.mdx, yarn.lock
=> chore: add test case for #391, disable unicorn/template-indent for prettier

package.json
=> chore: add workaround for `prerelease-next`

package.json, packages/eslint-mdx/package.json, packages/eslint-plugin-mdx/package.json, yarn.lock
=> fix: add missing unist-util-visit and vfile deps

.gitattributes, .github/workflows/ci.yml, package.json, test/helpers.test.ts, tsconfig.base.json, tsconfig.json, tsconfig.lib.json, yarn.lock
=> chore: bump @1stg/lib-config

.changeset/sharp-carpets-perform.md, packages/eslint-mdx/src/helpers.ts, packages/eslint-mdx/src/index.ts, packages/eslint-mdx/src/parser.ts, packages/eslint-mdx/src/sync.ts
=> fix: resolve circular imports in worker

.changeset/khaki-squids-leave.md, packages/eslint-mdx/src/tokens.ts, packages/eslint-mdx/src/worker.ts, test/__snapshots__/fixtures.test.ts.snap, test/__snapshots__/parser.test.ts.snap, test/fixtures/429.mdx
=> fix: parse error on void boolean attributes

.changeset/proud-trainers-sort.md, packages/eslint-mdx/src/helpers.ts
=> fix: handle pure ESM robustly

.changeset/eight-emus-lay.md, packages/eslint-mdx/src/worker.ts, test/__snapshots__/fixtures.test.ts.snap, test/__snapshots__/parser.test.ts.snap, test/fixtures/445.mdx
=> fix: jsx name could be namespace or member expression

.github/workflows/release.yml, package.json
*   [ ] If applicable, I’ve added docs and tests
See https://github.com/mdx-js/eslint-mdx/pull/492#issuecomment-1866471096
=> ci: enable `NPM_TOKEN` for releasing automatically

.changeset/poor-lions-buy.md, packages/eslint-mdx/src/parser.ts
=> chore: log error details on `--debug` flag enabled

.changeset/rich-pumas-add.md, packages/eslint-mdx/package.json, packages/eslint-plugin-mdx/package.json
https://nodejs.org/api/packages.html#conditional-exports
For `require(esm)`
=> chore: add `module-sync` entry

.changeset/sour-icons-complain.md, package.json, packages/eslint-plugin-mdx/src/from-markdown.ts, packages/eslint-plugin-mdx/src/processors/markdown.ts, test/__snapshots__/fixtures.test.ts.snap, test/__snapshots__/parser.test.ts.snap, test/fixtures/576.mdx, yarn.lock
=> fix: use unified `performSyncWork` for parsing with remark config
